-- IATA 공항 코드 매핑 초기 데이터
-- iata_mappings 테이블 생성(schema.pg.sql) 후 1회 실행
-- ON CONFLICT DO NOTHING → 중복 실행해도 안전

INSERT INTO iata_mappings (destination_name, country_code, iata_code, notes) VALUES
-- 동남아
('방콕',                 'th', 'BKK', NULL),
('아유타야(방콕)',       'th', 'BKK', '아유타야는 방콕 수완나품 공항 이용'),
('치앙마이',            'th', 'CNX', NULL),
('치앙마이(축등 축제)', 'th', 'CNX', NULL),
('하노이',              'vn', 'HAN', NULL),
('다낭',                'vn', 'DAD', NULL),
('나트랑',              'vn', 'CXR', NULL),
('후에',                'vn', 'HUI', NULL),
('싱가포르',            'sg', 'SIN', NULL),
('발리',                'id', 'DPS', NULL),
('발리(우붓)',           'id', 'DPS', '우붓은 덴파사르(DPS) 공항 이용'),
('길리 트라왕안',        'id', 'LOP', '롬복 국제공항'),
('세부',                'ph', 'CEB', NULL),
('앙코르와트',          'kh', 'REP', '씨엠립 국제공항'),
-- 동북아
('도쿄',                'jp', 'NRT', NULL),
('오사카',              'jp', 'KIX', NULL),
('교토',                'jp', 'KIX', '교토는 오사카 간사이(KIX) 공항 이용'),
('교토(봄 절정)',       'jp', 'KIX', NULL),
('삿포로',              'jp', 'CTS', NULL),
('삿포로(겨울)',        'jp', 'CTS', NULL),
('삿포로(라벤더)',      'jp', 'CTS', NULL),
('타이베이',            'tw', 'TPE', NULL),
('상하이',              'cn', 'PVG', NULL),
('장가계',              'cn', 'DYG', NULL),
-- 중동
('두바이',              'ae', 'DXB', NULL),
('이스탄불',            'tr', 'IST', NULL),
('보드룸',              'tr', 'BJV', NULL),
-- 인도양
('몰디브',              'mv', 'MLE', NULL),
-- 남아시아
('스리랑카',            'lk', 'CMB', '콜롬보 반다라나이케 공항'),
('다르질링',            'in', 'IXB', '바그도그라 공항'),
('라다크',              'in', 'IXL', '레 공항, 노선 없을 수 있음'),
('부탄(팀푸)',           'bt', 'PBH', '파로 공항, 노선 제한적'),
-- 오세아니아
('시드니',              'au', 'SYD', NULL),
-- 러시아
('블라디보스토크',      'ru', 'VVO', NULL),
-- 동유럽
('프라하',              'cz', 'PRG', NULL),
('부다페스트',          'hu', 'BUD', NULL),
('코토르',              'me', 'TIV', '티바트 공항'),
('두브로브니크',        'hr', 'DBV', NULL),
('두브로브니크(섬 호핑)', 'hr', 'DBV', NULL),
-- 동남아(미얀마)
('바간',                'mm', 'NYU', '냥우 공항, 노선 없을 수 있음'),
-- 서유럽
('파리',                'fr', 'CDG', NULL),
('스트라스부르',        'fr', 'SXB', NULL),
('암스테르담',          'nl', 'AMS', NULL),
('로마',                'it', 'FCO', NULL),
('베니스',              'it', 'VCE', NULL),
('피렌체',              'it', 'FLR', NULL),
('피렌체(비수기)',      'it', 'FLR', NULL),
('피렌체(토스카나)',    'it', 'FLR', NULL),
('포르토피노',          'it', 'GOA', '제노바 크리스토포로 콜롬보 공항'),
('바르셀로나',          'es', 'BCN', NULL),
('세비야',              'es', 'SVQ', NULL),
('테네리페',            'es', 'TFS', '테네리페 수르/레이나 소피아 공항'),
('리스본',              'pt', 'LIS', NULL),
('리스본(가을)',        'pt', 'LIS', NULL),
('포르투',              'pt', 'OPO', NULL),
('알가르베',            'pt', 'FAO', '파루 국제공항'),
('베르겐',              'no', 'BGO', NULL),
('코펜하겐',            'dk', 'CPH', NULL),
('더블린',              'ie', 'DUB', NULL),
('에든버러',            'gb', 'EDI', NULL),
('스코틀랜드 하이랜드', 'gb', 'GLA', '글래스고 국제공항'),
('뮌헨(옥토버페스트)',  'de', 'MUC', NULL),
('인터라켄',            'ch', 'ZRH', '취리히 공항 경유'),
('비엔나(크리스마스)',  'at', 'VIE', NULL),
('아테네+미코노스',     'gr', 'ATH', '아테네 경유 미코노스'),
('산토리니',            'gr', 'JTR', '티라/산토리니 공항'),
('레이캬비크',          'is', 'KEF', '케플라비크 국제공항'),
('라플란드(핀란드)',    'fi', 'RVN', '로바니에미 공항'),
-- 아프리카
('마라케시',            'ma', 'RAK', NULL),
('마라케시(가을)',      'ma', 'RAK', NULL),
-- 북미
('뉴욕',                'us', 'JFK', NULL),
('뉴욕(봄)',            'us', 'JFK', NULL),
('뉴욕(크리스마스&새해)', 'us', 'JFK', NULL),
('뉴올리언스',          'us', 'MSY', NULL),
('뉴올리언스(가을)',    'us', 'MSY', NULL),
('보스턴(뉴잉글랜드)', 'us', 'BOS', NULL),
('샌프란시스코',        'us', 'SFO', NULL),
('포틀랜드',            'us', 'PDX', NULL),
('마우이(하와이)',      'us', 'OGG', NULL),
('괌',                  'us', 'GUM', NULL),
('밴쿠버',              'ca', 'YVR', NULL),
('밴프',                'ca', 'YYC', '캘거리 공항 경유'),
-- 중미·카리브
('아바나',              'cu', 'HAV', '노선 없을 수 있음 (미국 제재 영향)'),
('칸쿤',                'mx', 'CUN', NULL),
('칸쿤(새해)',          'mx', 'CUN', NULL),
('멕시코시티',          'mx', 'MEX', NULL),
('오악사카',            'mx', 'OAX', NULL),
('코스타리카',          'cr', 'SJO', '후안 산타마리아 국제공항'),
-- 남미
('리우데자네이루',      'br', 'GIG', NULL),
('리우데자네이루(새해)', 'br', 'GIG', NULL),
('판타나우',            'br', 'CGB', '마레샬 론동 공항 (쿠이아바)'),
('부에노스아이레스',    'ar', 'EZE', NULL),
('파타고니아',          'ar', 'FTE', '엘 칼라파테 공항'),
('마추픽추',            'pe', 'LIM', '리마 호르헤 차베스 공항 경유'),
('쿠스코',              'pe', 'CUZ', NULL),
('갈라파고스(키토)',    'ec', 'UIO', '키토 마리스칼 수크레 공항'),
('카르타헤나',          'co', 'CTG', NULL),
('메데진',              'co', 'MDE', NULL),
('우유니',              'bo', 'ORU', '오루로 후안 멘도사 공항'),
('아타카마(산티아고)',  'cl', 'SCL', '산티아고 코모도로 아르투로 메리노 베니테스 공항')
ON CONFLICT (destination_name, country_code) DO NOTHING;
